journal_abbrev: GRL
region: Piton de la Fournaise, La Réunion
network: PF
short_description: Single-station SC + AC, 4 frequency bands
msnoise_version_min: 2.0.0
levels_available: [preprocess, cc, stack, mwcs, dvv]
data_open: true
uses_msnoise: true
validated: false
