#!/usr/bin/env python3
"""Generate _schema/project.schema.yaml from MSNoise's config CSV files.

Run after installing MSNoise:
    python scripts/generate_project_schema.py

The generated schema validates:
  - msnoise_project_version: 1 (required)
  - Top-level step keys match known category patterns (global, preprocess, cc, ...)
  - Per-category: known keys, types, and enum values where defined
  - Special top-level keys: data_sources (list), stations (object)
  - after: string or list of strings (cross-references not validated)
"""
import csv
import io
import pathlib

import yaml

import os
if "MSNOISE_CONFIG_DIR" in os.environ:
    config_dir = pathlib.Path(os.environ["MSNOISE_CONFIG_DIR"])
else:
    try:
        import importlib.resources as ilr
        config_dir = pathlib.Path(str(ilr.files("msnoise"))) / "config"
    except Exception:
        import msnoise
        config_dir = pathlib.Path(msnoise.__file__).parent / "config"

OUT = pathlib.Path(__file__).parent.parent / "_schema" / "project.schema.yaml"

# ── Category name → CSV file stem mapping ───────────────────────────────────
CATEGORIES = {
    "global":          "config_global",
    "preprocess":      "config_preprocess",
    "cc":              "config_cc",
    "filter":          "config_filter",
    "stack":           "config_stack",
    "refstack":        "config_refstack",
    "mwcs":            "config_mwcs",
    "mwcs_dtt":        "config_mwcs_dtt",
    "mwcs_dtt_dvv":    "config_mwcs_dtt_dvv",
    "stretching":      "config_stretching",
    "stretching_dvv":  "config_stretching_dvv",
    "wavelet":         "config_wavelet",
    "wavelet_dtt":     "config_wavelet_dtt",
    "wavelet_dtt_dvv": "config_wavelet_dtt_dvv",
    "psd":             "config_psd",
    "psd_rms":         "config_psd_rms",
}


def parse_csv(path: pathlib.Path) -> list[dict]:
    rows = []
    with open(path, newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            rows.append(row)
    return rows


def field_schema(row: dict) -> dict:
    """Convert a CSV row to a JSON Schema fragment."""
    typ = row.get("type", "str").strip()
    possible = (row.get("possible_values") or "").strip()

    if typ == "bool":
        # MSNoise bools are Y/N strings (or True/False for wavelet)
        if possible in ("True/False", "true/false"):
            return {"type": "boolean"}
        return {"type": "string", "enum": ["Y", "N"]}

    if typ == "int":
        s = {"type": "integer"}
    elif typ == "float":
        s = {"type": "number"}
    elif typ in ("str", "eval", ""):
        s = {"type": "string"}
    else:
        s = {"type": "string"}

    if possible and "/" in possible and typ == "str":
        values = [v.strip() for v in possible.split("/") if v.strip()]
        if values:
            s["enum"] = values

    return s


def category_schema(rows: list[dict]) -> dict:
    """Build the JSON Schema object for one category's config keys."""
    props = {
        "after": {
            "oneOf": [
                {"type": "string"},
                {"type": "array", "items": {"type": "string"}},
            ]
        }
    }
    for row in rows:
        name = row["name"].strip()
        if not name:
            continue
        props[name] = field_schema(row)
        desc = row.get("definition", "").strip()
        if desc:
            props[name]["description"] = desc[:200]  # truncate for readability

    return {
        "type": "object",
        "additionalProperties": False,
        "properties": props,
    }


def build_schema() -> dict:
    # Build per-category schemas
    cat_schemas = {}
    missing = []
    for cat, stem in CATEGORIES.items():
        csv_path = config_dir / f"{stem}.csv"
        if not csv_path.exists():
            missing.append(str(csv_path))
            continue
        rows = parse_csv(csv_path)
        cat_schemas[cat] = category_schema(rows)

    if missing:
        print(f"WARNING: {len(missing)} CSV(s) not found — skipped:")
        for m in missing:
            print(f"  {m}")

    # Build pattern properties: one entry per category, matching <cat>_\d+
    pattern_props = {}
    for cat, schema in cat_schemas.items():
        # escape underscore — not needed in JSON Schema regex but be explicit
        pattern = f"^{cat}_\\d+$"
        pattern_props[pattern] = schema

    schema = {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": "MSNoise project.yaml",
        "description": (
            "Validates an MSNoise 2.x project.yaml file. "
            "Auto-generated by scripts/generate_project_schema.py — do not edit manually."
        ),
        "type": "object",
        "required": ["msnoise_project_version"],
        "properties": {
            "msnoise_project_version": {
                "type": "integer",
                "const": 1,
                "description": "Must be 1.",
            },
            "data_sources": {
                "type": "array",
                "items": {
                    "type": "object",
                    "required": ["name", "uri"],
                    "properties": {
                        "name":           {"type": "string",
                                           "description": "Unique source name; 'local' is reserved."},
                        "uri":            {"type": "string"},
                        "data_structure": {"type": "string", "enum": ["SDS", "PDF"]},
                        "network":        {"type": "string"},
                        "channels":       {"type": "string"},
                        "auth_env":       {"type": "string"},
                        "archive_format": {"type": ["string", "null"]},
                    },
                    "additionalProperties": False,
                },
            },
            "stations": {
                "oneOf": [
                    {
                        "type": "object",
                        "properties": {
                            "station_endpoint": {"type": "string"},
                        },
                        "additionalProperties": True,
                    },
                    {
                        "type": "array",
                        "items": {"type": "object"},
                    },
                ],
                "description": "Either {station_endpoint: url} or a list of station dicts.",
            },
        },
        "patternProperties": pattern_props,
        "additionalProperties": False,
        "unevaluatedProperties": False,
    }
    return schema


def dump_yaml(data: dict) -> str:
    """Dump with a wide line width to avoid wrapping enum lists."""
    return yaml.dump(data, allow_unicode=True, sort_keys=False,
                     default_flow_style=False, width=120)


if __name__ == "__main__":
    schema = build_schema()
    header = (
        "# MSNoise project.yaml JSON Schema\n"
        "# Auto-generated by scripts/generate_project_schema.py — do not edit manually.\n"
        "# Regenerate after updating MSNoise: python scripts/generate_project_schema.py\n\n"
    )
    OUT.write_text(header + dump_yaml(schema), encoding="utf-8")
    cats = len([k for k in schema["patternProperties"]])
    print(f"Written: {OUT}  ({cats} categories)")
