journal_abbrev: SRL
region: Piton de la Fournaise, La Réunion
network: YA
short_description: Foundation of MSNoise, CC-ZZ only
msnoise_version_min: 2.0.0
levels_available: [dvv]
data_open: true
uses_msnoise: true
validated: false
